language: generic
sudo: require
services:
  - docker

before_install:
  - docker build -t fernandoreimberg/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true fernandoreimberg/docker-react npm run test -- --coverage  